import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service - Synapse",
  description: "Terms and conditions for using Synapse's AI-powered learning platform",
};

export default function TermsPage() {
  return (
    <div className="container mx-auto px-4 py-16 max-w-4xl">
      <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>
      <div className="prose prose-gray dark:prose-invert max-w-none">
        <p className="text-lg text-muted-foreground mb-8">
          Last updated: {new Date().toLocaleDateString()}
        </p>

        <section className="mb-12">
          <h2 className="text-2xl font-semibold mb-4">1. Acceptance of Terms</h2>
          <p>
            By accessing or using Synapse ("the Service"), you agree to be bound by these Terms of Service 
            ("Terms"). If you disagree with any part of these terms, you do not have permission to access 
            the Service.
          </p>
        </section>

        <section className="mb-12">
          <h2 className="text-2xl font-semibold mb-4">2. Description of Service</h2>
          <p>
            Synapse is an AI-powered learning platform that provides:
          </p>
          <ul className="list-disc pl-6 space-y-2 mt-4">
            <li>Document processing and analysis</li>
            <li>AI-generated summaries, quizzes, and flashcards</li>
            <li>Interactive learning features including "Teach Me" mode</li>
            <li>Audio transcription and voice synthesis</li>
            <li>Progress tracking and learning analytics</li>
          </ul>
        </section>

        <section className="mb-12">
          <h2 className="text-2xl font-semibold mb-4">3. User Accounts</h2>
          <h3 className="text-xl font-medium mb-3">Account Creation</h3>
          <ul className="list-disc pl-6 space-y-2">
            <li>You must provide accurate and complete information</li>
            <li>You are responsible for maintaining account security</li>
            <li>You must be at least 13 years old to use the Service</li>
            <li>One person or legal entity may not maintain multiple accounts</li>
          </ul>
          
          <h3 className="text-xl font-medium mb-3 mt-6">Account Responsibilities</h3>
          <p>
            You are responsible for all activities that occur under your account. Notify us immediately 
            of any unauthorized use or security breach.
          </p>
        </section>

        <section className="mb-12">
          <h2 className="text-2xl font-semibold mb-4">4. Acceptable Use Policy</h2>
          <p className="mb-4">You agree not to use the Service to:</p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Violate any laws or regulations</li>
            <li>Upload malicious content or software</li>
            <li>Infringe on intellectual property rights</li>
            <li>Harass, abuse, or harm others</li>
            <li>Attempt to bypass usage limits or security measures</li>
            <li>Use the Service for any illegal or unauthorized purpose</li>
            <li>Resell or redistribute the Service without permission</li>
            <li>Generate content that violates OpenAI's usage policies</li>
          </ul>
        </section>

        <section className="mb-12">
          <h2 className="text-2xl font-semibold mb-4">5. Intellectual Property</h2>
          <h3 className="text-xl font-medium mb-3">Your Content</h3>
          <p>
            You retain ownership of content you upload to Synapse. By uploading content, you grant us 
            a license to process, analyze, and display it within the Service for the purpose of providing 
            our features.
          </p>
          
          <h3 className="text-xl font-medium mb-3 mt-6">Our Content</h3>
          <p>
            The Service, including its design, features, and content (excluding user content), is owned 
            by Synapse and protected by intellectual property laws. You may not copy, modify, or reverse 
            engineer any part of the Service.
          </p>
          
          <h3 className="text-xl font-medium mb-3 mt-6">AI-Generated Content</h3>
          <p>
            Content generated by our AI features is provided for educational purposes. While we strive 
            for accuracy, AI-generated content may contain errors and should be verified independently.
          </p>
        </section>

        <section className="mb-12">
          <h2 className="text-2xl font-semibold mb-4">6. Subscription Terms</h2>
          <h3 className="text-xl font-medium mb-3">Pricing</h3>
          <ul className="list-disc pl-6 space-y-2">
            <li><strong>Free Tier:</strong> Limited features as described on our pricing page</li>
            <li><strong>Pro Tier:</strong> $12.99/month with unlimited features</li>
          </ul>
          
          <h3 className="text-xl font-medium mb-3 mt-6">Billing</h3>
          <ul className="list-disc pl-6 space-y-2">
            <li>Subscriptions are billed monthly in advance</li>
            <li>Payments are processed securely through Stripe</li>
            <li>Prices may change with 30 days notice</li>
            <li>No refunds for partial months</li>
          </ul>
          
          <h3 className="text-xl font-medium mb-3 mt-6">Cancellation</h3>
          <p>
            You may cancel your subscription at any time. Access continues until the end of the current 
            billing period. Upon cancellation, your account reverts to the free tier.
          </p>
        </section>

        <section className="mb-12">
          <h2 className="text-2xl font-semibold mb-4">7. Limitation of Liability</h2>
          <p>
            TO THE MAXIMUM EXTENT PERMITTED BY LAW, SYNAPSE SHALL NOT BE LIABLE FOR ANY INDIRECT, 
            INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES, OR ANY LOSS OF PROFITS OR REVENUES, 
            WHETHER INCURRED DIRECTLY OR INDIRECTLY, OR ANY LOSS OF DATA, USE, GOODWILL, OR OTHER 
            INTANGIBLE LOSSES.
          </p>
          <p className="mt-4">
            In no event shall our aggregate liability exceed the amounts actually paid by you in the 
            twelve (12) months preceding the event giving rise to the liability.
          </p>
        </section>

        <section className="mb-12">
          <h2 className="text-2xl font-semibold mb-4">8. Disclaimer of Warranties</h2>
          <p>
            THE SERVICE IS PROVIDED "AS IS" AND "AS AVAILABLE" WITHOUT WARRANTIES OF ANY KIND, EITHER 
            EXPRESS OR IMPLIED. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, 
            OR COMPLETELY SECURE.
          </p>
        </section>

        <section className="mb-12">
          <h2 className="text-2xl font-semibold mb-4">9. Indemnification</h2>
          <p>
            You agree to defend, indemnify, and hold harmless Synapse and its officers, directors, 
            employees, and agents from any claims, damages, obligations, losses, liabilities, costs, 
            or expenses arising from:
          </p>
          <ul className="list-disc pl-6 space-y-2 mt-4">
            <li>Your use of the Service</li>
            <li>Your violation of these Terms</li>
            <li>Your violation of any third-party rights</li>
          </ul>
        </section>

        <section className="mb-12">
          <h2 className="text-2xl font-semibold mb-4">10. Termination</h2>
          <p>
            We may terminate or suspend your account immediately, without prior notice or liability, 
            for any reason, including breach of these Terms. Upon termination, your right to use the 
            Service will cease immediately.
          </p>
        </section>

        <section className="mb-12">
          <h2 className="text-2xl font-semibold mb-4">11. Governing Law</h2>
          <p>
            These Terms shall be governed by and construed in accordance with the laws of California, 
            United States, without regard to its conflict of law provisions. Any disputes shall be 
            resolved in the courts of San Francisco County, California.
          </p>
        </section>

        <section className="mb-12">
          <h2 className="text-2xl font-semibold mb-4">12. Changes to Terms</h2>
          <p>
            We reserve the right to modify these Terms at any time. If we make material changes, we 
            will notify you via email or through the Service. Your continued use after changes 
            constitutes acceptance of the new Terms.
          </p>
        </section>

        <section className="mb-12">
          <h2 className="text-2xl font-semibold mb-4">13. Contact Information</h2>
          <p className="mb-4">
            For questions about these Terms, please contact us:
          </p>
          <div className="bg-muted p-6 rounded-lg">
            <p><strong>Email:</strong> legal@synapse.com</p>
            <p><strong>Address:</strong> Synapse, Inc.<br />123 AI Learning Lane<br />San Francisco, CA 94105</p>
          </div>
        </section>

        <section className="mb-12">
          <h2 className="text-2xl font-semibold mb-4">14. Entire Agreement</h2>
          <p>
            These Terms constitute the entire agreement between you and Synapse regarding the Service 
            and supersede any prior agreements.
          </p>
        </section>
      </div>
    </div>
  );
}